workflow:
  name: "batch_ingestion_sts_workflow"

gcp:
  project_id: "sandbox-aboudia"
  location: "europe-west1"

source:
  repository: "ahmedboudia-dgc/dataplatform-workflows"
  workflow_file: "batch-ingestion-sts-workflow/batch_ingestion_sts_workflow.yaml"

version:
  tag: ""

parameters: {}
